endpoint: wss://acala-rpc.aca-api.network
#endpoint: ws://192.168.50.62:8000
#endpoint: wss://chopsticks-acala.aca-dev.network/acala
mock-signature-host: true
#block: 9026116
#block: ${env.ACALA_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5
wasm-override: /configs/acala_runtime.2300.compact.compressed.wasm
#wasm-override: /home/x/source/zjb0807/snowbridge/configs/acala_runtime.2300.compact.compressed.wasm
#resume: true

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 246gNkjCexYRsCpdjtVhz35sHjcb21jpqipzT9u4uwKV8iEE
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 249LSvsEyxS4VpEJGg62yhYA7sHy1KcgGW6KzACBCLW1RsZF
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 21y4X7QDByUjnu5KX9W1H5TbG2wTLPDbhYFHqc4v6Q1nTBnu
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 265dERKLvMFwWWvtGNUjQBrHFTT88VcEtb5QYh2Zuj79UGMf
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 21XH88Kd5vDLkrZMb4D2eYJAB9yKbycfkYBqAaD1wQQi1uJ8
        - providers: 1
          data:
            free: 1000000000000000
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: AUSD
        - free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: DOT
        - free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: LDOT
        - free: 1000000000000000
  GeneralCouncil:
    Members:
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - 246gNkjCexYRsCpdjtVhz35sHjcb21jpqipzT9u4uwKV8iEE
      - 249LSvsEyxS4VpEJGg62yhYA7sHy1KcgGW6KzACBCLW1RsZF
      - 21y4X7QDByUjnu5KX9W1H5TbG2wTLPDbhYFHqc4v6Q1nTBnu
      - 265dERKLvMFwWWvtGNUjQBrHFTT88VcEtb5QYh2Zuj79UGMf
      - 21XH88Kd5vDLkrZMb4D2eYJAB9yKbycfkYBqAaD1wQQi1uJ8
  TechnicalCommittee:
    Members:
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - 246gNkjCexYRsCpdjtVhz35sHjcb21jpqipzT9u4uwKV8iEE
      - 249LSvsEyxS4VpEJGg62yhYA7sHy1KcgGW6KzACBCLW1RsZF
  EvmAccounts:
    EvmAddresses:
    - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - '0x75E480dB528101a381Ce68544611C169Ad7EB342'
    Accounts:
    - - - '0x75E480dB528101a381Ce68544611C169Ad7EB342'
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
  Homa:
    NominateIntervalEra: 0
  XcmInterface:
    XcmDestWeightAndFee:
      - [[HomaNominate], [{refTime: 5000000000, proofSize: 131072}, 5000000000]]
