endpoint: wss://polkadot-asset-hub-rpc.polkadot.io
#endpoint: wss://chopsticks-acala.aca-dev.network/assethub
mock-signature-host: true
#block: 9468545
#block: ${env.POLKADOT_ASSET_HUB_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5
wasm-override: /configs/asset_hub_polkadot_runtime.1005001.compact.compressed.wasm
#wasm-override: /home/x/source/zjb0807/snowbridge/configs/asset_hub_polkadot_runtime.1005001.compact.compressed.wasm

import-storage:
  System:
    Account:
      - [[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { providers: 1, data: { free: 1000000000000000 }}]
      - [[12pw22Qyy3o28BLshjce9yrSMs3fhSiLsAjqLPAzGktbXYV7], { providers: 1, data: { free: '46104761056640463', reserved: '200410000000', frozen: '46101975004999542'}}]
      - [[13cKp89Msu7M2PiaCuuGr1BzAsD5V3vaVbDMs3YtjMZHdGwR], { providers: 1, data: { free: '31888059184720240', reserved: '3400000000000', frozen: '0'}}]
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[1337, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[21], { supply: 1000000000 }]]
  ForeignAssets:
    Account:
      - [[{ parents: 2, interior: { X2: [{ GlobalConsensus: { Ethereum: { chainId: 1 }}}, { AccountKey20: { network: null, key: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' }}]}}, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: '1000000000000000000000', status: Liquid, reason: Consumer, extra: null }]
      - [
          [
            { parents: 2, interior: { X1: [{ GlobalConsensus: { Ethereum: { chainId: 1 } } }] } },
            5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
          ],
          { balance: "100000000000000000000" },
        ]
  #Staking:
  #  Validators:
  #    - [[1d6po5LATxuHeAUTSRd61LGA6QWJ7dJRzi852kojKFLbL3t], { commission: 0, blocked: false }]
  #    - [[14N5nJ4oR4Wj36DsBcPLh1JqjvrM2Uf23No2yc2ojjCvSC24], { commission: 0, blocked: false }]
  #    - [[14bUYpiF2oxVpmXDnFxBipSi4m9zYBThMZoLpY8bRQrPQNG1], { commission: 0, blocked: false }]
  #    - [[14zf4PVrmW7LwLptMkZwhKK2fwroFnMpMLrKiy5jpYCMZBwW], { commission: 0, blocked: false }]
  #    - [[1569aqCBma2m4TuUe1MxEs8EXBAZFCmwwcZMLde6HNbimuW8], { commission: 0, blocked: false }]
  #    - [[15XY7oJ99hVscy5jS3zUh5M3H6sxfccovyTVCPt15DuXCRAF], { commission: 0, blocked: false }]
  #    - [[15iA5hpjUecWBbf38Nfegwmtyux25o3LrGaNodfZDxq5nXXE], { commission: 0, blocked: false }]
  #    - [[16NWoCHEY67DDHCLe76QhgKD3AAcRQtarY54FFQQaJeftJNu], { commission: 0, blocked: false }]
  #    - [[15faP4KV8Puvtex2WXnhUoeedhNpTPt4jWcAmZVsUuNMVvUX], { commission: 0, blocked: false }]
  #    - [[14AakQ4jAmr2ytcrhfmaiHMpj5F9cR6wK1jRrdfC3N1oTbUz], { commission: 0, blocked: false }]
  #  Bonded:
  #    - [[12pw22Qyy3o28BLshjce9yrSMs3fhSiLsAjqLPAzGktbXYV7], 12pw22Qyy3o28BLshjce9yrSMs3fhSiLsAjqLPAzGktbXYV7]
  #  ledger:
  #    - [
  #        [12pw22Qyy3o28BLshjce9yrSMs3fhSiLsAjqLPAzGktbXYV7],
  #        {
  #          stash: 12pw22Qyy3o28BLshjce9yrSMs3fhSiLsAjqLPAzGktbXYV7,
  #          total: '46089842061525133',
  #          active: '42618337842051333',
  #          unlocking: [
  #            {
  #              value: '1133844989535540',
  #              era: 1872
  #            },
  #            {
  #              value: '1344224653780',
  #              era: 1874
  #            },
  #            {
  #              value: '17771827209997',
  #              era: 1876
  #            },
  #            {
  #              value: '16958447545257',
  #              era: 1877
  #            },
  #            {
  #              value: '184943273868892',
  #              era: 1878
  #            },
  #            {
  #              value: '413412872141',
  #              era: 1879
  #            },
  #            {
  #              value: '351965507879238',
  #              era: 1880
  #            },
  #            {
  #              value: '46970182113266',
  #              era: 1881
  #            },
  #            {
  #              value: '99129426941179',
  #              era: 1882
  #            },
  #            {
  #              value: '109664158945638',
  #              era: 1886
  #            },
  #            {
  #              value: '2924577587526',
  #              era: 1887
  #            },
  #            {
  #              value: '387132826378',
  #              era: 1888
  #            },
  #            {
  #              value: '5111759292783',
  #              era: 1889
  #            },
  #            {
  #              value: '4562923830023',
  #              era: 1890,
  #            },
  #            {
  #              value: '8813734252312',
  #              era: 1893
  #            },
  #            {
  #              value: '139948127216953',
  #              era: 1894
  #            },
  #            {
  #              value: '91995244397781',
  #              era: 1895
  #            },
  #            {
  #              value: '1182402471390744',
  #              era: 1896
  #            },
  #            {
  #              value: '72352797114372',
  #              era: 1897
  #            }
  #          ]
  #        }
  #      ]
