endpoint: wss://westend-asset-hub-rpc.polkadot.io
#endpoint: wss://chopsticks-acala.aca-dev.network/assethub
mock-signature-host: true
block: ${env.WESTEND_ASSET_HUB_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5
#wasm-override: /configs/asset_hub_westend_runtime.1018012.compact.compressed.wasm
#wasm-override: /home/x/source/zjb0807/snowbridge/configs/asset_hub_westend_runtime.1018012.compact.compressed.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[1337, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[21], { supply: 1000000000 }]]
  ForeignAssets:
    Account:
      - [[{ parents: 2, interior: { X2: [{ GlobalConsensus: { Ethereum: { chainId: 1 }}}, { AccountKey20: { network: null, key: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' }}]}}, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: '1000000000000000000000', status: Liquid, reason: Consumer, extra: null }]
      - [
          [
            { parents: 2, interior: { X1: [{ GlobalConsensus: { Ethereum: { chainId: 1 } } }] } },
            5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
          ],
          { balance: "100000000000000000000" },
        ]
